### ISSUE TITLE
Not working in the new update

### ISSUE THREAD

**Issue by ruwaida99** [henryefranks/pac-bar#10] opened 2020-01-18 00:10 UTC
<img width="436" alt="Screenshot 2020-01-18 at 12 09 53 am" src="https://user-images.githubusercontent.com/60021211/72654301-e5154a00-3986-11ea-8bbe-7e426a53d8dc.png">

**Comment by henryefranks** [comment] 2020-01-18 12:56
This looks like it's to do with Apple's new insistence on notarisation. I'll look into getting the app notarised so this doesn't become a recurring problem in future, but in the meantime does it work if you right click and select 'open'?

**Comment by mari-rmrz** [comment] 2020-01-27 01:54
I'm getting the same problem. I can open it with right click --> Open but I don't get anything in the touch bar. Just the window showing me my score

**Comment by henryefranks** [comment] 2020-08-20 17:07
This actually looks like a duplicate of #7, so I'll close it for now. I'll only update that issue going forward with any further details on the problem.

**Closed by henryefranks** 2020-08-20 17:07 UTC
